### ISSUE TITLE
[QUESTION] Flow failures and external events

### ISSUE THREAD

**Issue by MrZoidberg** [go-pkgz/flow#3]
Hi @umputun. I'm looking for options to build a Go-based workflow to provision cloud infrastructure during runtime as a series of steps. `Flow` looks like a good candidate for me. The only concern I have is that I would like to have the ability to resume/restart after failure (service halt) and do some rollback operations when a flow cannot be completed. Is this something you don't care about in this package or build on top? 
A second question I have is the possibility to wait for an external event to proceed with flow steps. Some of my steps need to be asynchronous that call async HTTP API and I need to wait for a webhook/queue event to resume the flow.

Thanks!

**Comment by umputun** [comment]
Well, the `Flow` is a low-level library that essentially connects a set of handlers and provides a safe way to execute each handler in separate goroutine(s). However, the functionality you describe is a part of the business logic you should implement as a part of a particular handler. For example, the restart/resume you have described will likely be a part of your implementation of a specific handler; the same goes for API calls. The `Flow` doesn't handle what is inside each handler but instead plumbs them together and orchestrates concurrent execution. 

I'm not even sure if the use case you described fits this library well. From what I understand, you need a sequential execution of multiple steps, but this library is all about concurrent/parallel execution.

Maybe you need something higher-level executing multiple steps with the ability to do something specific on failure and run some conditional checks? Take a look at my other project https://github.com/umputun/spot, to me it sounds much closer to what you described.

**Comment by MrZoidberg** [comment]
Thank you for so detailed answer. Probably I need to check for more suitable and high-level Go libraries. Closing this thread now.
